Add new component, tests and documentation for externereferenz
Hochfrequenz/BO4E-python pull request #15
Opened 2020-11-17 16:34 UTC by hf-krechan

Add externereferenz component to bo4e python package

2020-11-17 16:55 UTC, hf-kklein requested changes
Prinzipiell OK, aber so steht das Ding/die COMponente ja noch sehr alleine da. Warum bindest du sie nicht gleich als optionale Liste im Geschäftsobjekt ein?

2020-11-17 16:55 UTC, hf-kklein commented on tests/test_externe_referenz.py
> +        er = ExterneReferenz(ex_ref_name="Hello", ex_ref_wert="World")
was würde passieren, wenn ich einem der dinger None zuweise? kannst du einen test schreiben, der das verhalten klar macht (und damit zeigt, dass es gewollt ist)?

2020-11-19 07:28 UTC, hf-kklein approved these changes

2020-11-19 18:47 UTC, hf-krechan commented
Mist, jetzt hab ich die `frozen=True` in diesem Branch entfernt. Kann man dies ohne große Schmerzen rückgängig machen?

2020-11-19 21:11 UTC, hf-kklein commented
>Mist, jetzt hab ich die frozen=True in diesem Branch entfernt. Kann man dies ohne große Schmerzen rückgängig machen?

revert commit? und dann ggf. cherry picken

2020-11-19 21:14 UTC, hf-kklein commented on tests/test_geschaeftsobjekt.py
> +            go = Geschaeftsobjekt(
```suggestion
            _ = Geschaeftsobjekt(
```

2020-11-19 21:14 UTC, hf-kklein commented on tox.ini
> +    tests/test_geschaeftsobjekt.py:F841
brauchst du glaube ich  nicht mehr, wenn du das discard assignment nimmst.

2020-11-20 06:43 UTC, hf-kklein commented
>revert commit? und dann ggf. cherry picken

erledigt. @hf-krechan : für deine saubere commit historie kannst du jetzt #16 squash mergen für alles was mit der Externen Referenz zusammenhängt und diesen hier für den frozen decorator

2020-11-20 08:23 UTC, hf-krechan commented on tox.ini
> +    tests/test_geschaeftsobjekt.py:F841
Das ist zu 100% korrekt.
Für Sie getestet ;)

2020-11-20 08:30 UTC, merged