🔨 Add postfach as alternative to strasse
Hochfrequenz/BO4E-python pull request #23
Opened 2020-12-07 15:42 UTC by hf-aschloegl

Before strasse and hausnummer were required fields and postfach optional. Since postfach is an alternative address option to strasse and hausnummer this was changed to either strasse and hausnummer or postfach being a required address field.

2020-12-07 15:51 UTC, hf-kklein requested changes

2020-12-07 15:51 UTC, hf-kklein commented on src/bo4e/com/adresse.py
> +    ) and instance.postfach is None:
```suggestion
        not instance.strasse or not instance.hausnummer) and not instance.postfach:
```
ich frage mich, ob es hier nicht genug oder sogar angebrachter wäre, zu prüfen ob das Feld "truethy" oder "falsy" ist. Z.B. ein leerer String `strasse = ""` wäre ja ähnlich falsch würde aber durchgehen.

2020-12-07 15:51 UTC, hf-kklein commented on src/bo4e/com/adresse.py
> +        raise ValueError("Only strasse and hausnummer or postfach are required.")
ist es denn so, dass postfächer _nie_ eine Strasse haben? AUch hier könnte man auf falsy/truethy prüfen und wäre vllt besser dran.

2020-12-07 15:51 UTC, hf-kklein commented on tests/test_adresse.py
> +            ),
```suggestion
            pytest.param(
                {
                    "postleitzahl": "82031",
                    "ort": "Grünwald",
                    "strasse": None,
                    "hausnummer": None,
                    "postfach": None,
                },
                "Either",
                id="Missing postfach",
            ),
                        pytest.param(
                {
                    "postleitzahl": "82031",
                    "ort": "Grünwald",
                    "strasse": None,
                    "hausnummer": None,
                    "postfach": "",
                },
                "Either",
                id="Not null but empty/falsy postfach",
            ),
```

2020-12-07 16:10 UTC, hf-aschloegl commented on src/bo4e/com/adresse.py
> +    ) and instance.postfach is None:
Na klar, viel besser. Wussten nicht, dass das so einfach ist ^^

2020-12-07 16:13 UTC, hf-aschloegl commented on src/bo4e/com/adresse.py
> +        raise ValueError("Only strasse and hausnummer or postfach are required.")
Soweit ich weiß haben die keine Straße, aber habe gerade gelernt, dass man auch auf die Postfachnummer verzichten kann, wenn es eine eigene Postleitzahl hat. Das habe ich noch nicht bedacht.

2020-12-07 16:21 UTC, hf-aschloegl commented on src/bo4e/com/adresse.py
> +        raise ValueError("Only strasse and hausnummer or postfach are required.")
![grafik](https://user-images.githubusercontent.com/73470827/101376132-7e579280-38b0-11eb-9ba8-c1d797dd0701.png)
Zumindest müssen sie laut edi@energy zumindest mal "Postfach" hinschreiben

2020-12-07 16:23 UTC, hf-kklein commented on src/bo4e/com/adresse.py
> +        raise ValueError("Only strasse and hausnummer or postfach are required.")
EDI@Energy != BO4E , wenn auch manchmal ähnlich.

2020-12-07 16:26 UTC, hf-aschloegl commented on src/bo4e/com/adresse.py
> +        raise ValueError("Only strasse and hausnummer or postfach are required.")
Ja, da hab ich noch mit dem mapping im Hinterkopf gedacht

2020-12-09 08:06 UTC, hf-krechan approved these changes

2020-12-09 08:31 UTC, hf-kklein approved these changes

2020-12-09 08:32 UTC, merged