Implement COM Ausschreibungsdetail
Hochfrequenz/BO4E-python pull request #259
Opened 2021-12-15 14:57 UTC by hf-kklein

fixes #142

2021-12-15 16:04 UTC, hf-aschloegl requested changes

2021-12-15 16:04 UTC, hf-aschloegl commented on tests/test_ausschreibungsdetail.py
> +        "ausschreibungsdetail, expected_json_dict",
Damit es nicht wieder heißt, der Reviewer wäre schuld, kannst du noch ein minimal attribute Test machen? ;)

2021-12-15 16:04 UTC, hf-aschloegl commented on tests/test_ausschreibungsdetail.py
> +        assert "missing 15 required" in str(excinfo.value)
Sollten doch nur 5 required sein?

2021-12-16 05:39 UTC, hf-kklein commented on src/bo4e/com/ausschreibungsdetail.py
> +    zeitraum: Zeitraum = attr.ib(validator=attr.validators.instance_of(Zeitraum))
https://github.com/Hochfrequenz/BO4E-python/pull/259/commits/e4c0af0a736475bf3189752697a4b4678848db71

2021-12-16 05:39 UTC, hf-kklein commented on tests/test_ausschreibungsdetail.py
> +        "ausschreibungsdetail, expected_json_dict",
https://github.com/Hochfrequenz/BO4E-python/pull/259/commits/9bac7ee76cfb4f7c3f6787ec39e932f2f032fea4

2021-12-16 05:39 UTC, hf-kklein commented on tests/test_ausschreibungsdetail.py
> +        assert "missing 15 required" in str(excinfo.value)
behoben

2021-12-20 07:55 UTC, hf-aschloegl approved these changes

2021-12-20 08:10 UTC, merged