Implement COM Ausschreibungslos
Hochfrequenz/BO4E-python pull request #298
Opened 2022-01-05 16:49 UTC by hf-kklein

2022-01-17 15:57 UTC, hf-aschloegl requested changes

2022-01-17 15:57 UTC, hf-aschloegl commented on src/bo4e/com/ausschreibungslos.py
> +    #: Bezeichnung des Loses
```suggestion
    #: Bezeichnung der Ausschreibung
```

2022-01-17 15:57 UTC, hf-aschloegl commented on src/bo4e/com/ausschreibungslos.py
> +    #:Die ausgeschriebenen Lieferstellen
```suggestion
    #: Die ausgeschriebenen Lieferstellen
```

2022-01-17 15:57 UTC, hf-aschloegl commented on src/bo4e/com/ausschreibungslos.py
> +    )
Ist der Lieferzeitraum nicht required? Also es steht mal wieder nichts an dem Pfeil, aber das haben wir ja bisher als eine 1 interpretiert oder?

2022-01-17 15:57 UTC, hf-aschloegl commented on tests/test_ausschreibungslos.py
> +        assert "missing 9 required" in str(excinfo.value)
Falls der lieferzeitraum doch required ist.
```suggestion
        assert "missing 10 required" in str(excinfo.value)
```

2022-01-17 15:59 UTC, hf-kklein commented on src/bo4e/com/ausschreibungslos.py
> +    )
ja du hast recht

2022-01-18 07:01 UTC, hf-kklein commented on src/bo4e/com/ausschreibungslos.py
> +    )
https://github.com/Hochfrequenz/BO4E-python/pull/298/commits/5a6ea57417460c97bffc157950c66e272ab46d10

2022-01-18 07:27 UTC, hf-aschloegl approved these changes

2022-01-18 07:27 UTC, merged