Implement COM Preisposition
Hochfrequenz/BO4E-python pull request #315
Opened 2022-01-10 08:11 UTC by hf-kklein

Fixes #182

2022-01-10 08:58 UTC, hf-kklein commented
before merging update #317  with changes from here.

2022-01-18 07:14 UTC, hf-aschloegl requested changes

2022-01-18 07:14 UTC, hf-aschloegl commented on src/bo4e/com/preisposition.py
> +
Hier fehlt noch die ArtikelID oder?

2022-01-18 16:37 UTC, hf-kklein commented on src/bo4e/com/preisposition.py
> +
https://github.com/Hochfrequenz/BO4E-python/pull/315/commits/e967384c5563672d01f6987639092b516c639b16

2022-01-18 16:50 UTC, hf-aschloegl approved these changes

2022-01-18 16:51 UTC, merged